#name, main, version and api are required
name: Gateworld
main: gw.Core
#remember version and api is string, don't write it like this: 1.0.0, or there will be an exception
version: "0.0.2"
api: ["1.0.0"]

load: POSTWORLD
author: Pryme8
description: A Adverture/Guild Realm Plugin
website: http://Pryme8.com
commands:
  player_reset_class:
    description: Resetting the Player Class
    usage: "/player_reset_class"
    permission: gateworld.command.player_reset_class
  player_choose_class_ranger:
    description: A Simple Class Choice
    usage: "/player_choose_class_ranger"
    permission: gateworld.command.player_choose_class_ranger
  player_choose_class_warrior:
    description: A Simple Class Choice
    usage: "/player_choose_class_warrior"
    permission: gateworld.command.player_choose_class_warrior
  player_choose_class_craftsman:
    description: A Simple Class Choice
    usage: "/player_choose_class_craftsman"
    permission: gateworld.command.player_choose_class_craftsman
  warp_to_main_start:
    description: Warp to the MainZone Starting Area
    usage: "/warp_to_main_start"
    permission: gateworld.command.warp_to_main_start
  main_back_to_start:
    description: Warp From the MainZone to Starting Area
    usage: "/main_back_to_start"
    permission: gateworld.command.main_back_to_start
  main_to_free_zone:
      description: Warp From the MainZone to FreeZone
      usage: "/main_to_free_zone"
      permission: gateworld.command.main_to_free_zone
  free_zone_to_main_zone:
    description: Warp From the FreeZone to MainZone
    usage: "/free_zone_to_main_zone"
    permission: gateworld.command.free_zone_to_main_zone
  create_new_guild:
    description: Create New Guild
    usage: "/create_new_guild"
    permission: gateworld.command.create_new_guild

permissions:
  gateworld.command.player_reset_class:
    description: "Resetting the Player Class"
    default: true
  gateworld.command.player_choose_class_ranger:
    description: "Ranger Class Choice"
    default: true
  gateworld.command.player_choose_class_warrior:
    description: "Warrior Class Choice"
    default: true
  gateworld.command.player_choose_class_craftsman:
    description: "Craftsman Class Choice"
    default: true
  gateworld.command.warp_to_main_start:
    description: "Warp to the MainZone Starting Area"
    default: true
  gateworld.command.main_back_to_start:
    description: "Warp From the MainZone to Starting Area"
    default: true
  gateworld.command.main_to_free_zone:
    description: "Warp From the MainZone to FreeZone"
    default: true
  gateworld.command.free_zone_to_main_zone:
    description: "Warp From the FreeZone to MainZone"
    default: true
  gateworld.command.create_new_guild:
    description: "Admin Create New Guild"
    default: true